### ISSUE TITLE
No response on specific URL

### ISSUE THREAD

**Issue by cure85** [duzun/hQuery.php#15]
Hi,

I have noticed a peculiar case when trying to get http://www.nameit.com

hQuery::fromUrl('http://www.nameit.com') returns false

On the demo nothing happens as well.

Best regards

**Comment by duzun** [comment]
The issue here is that nameit.com keeps redirecting hQuery again and again because hQuery doesn't preserve cookies.
By default hQuery follows up to 7 redirects, then returns `false` as there is no response body.

I'm planing to implement cookies soon, at least for such cases like this one (in mem cookies).

Thanks for pointing it out!
