### ISSUE TITLE
Warning: gzdecode(): data error

### ISSUE THREAD

**Issue by ValenokPC** [duzun/hQuery.php#24]
Warning: gzdecode(): data error in ./../hquery.php on line 2272

**Comment by duzun** [comment]
It is most likely an issue with the page you are trying to access. 
I can't tell what exactly is wrong without a context.

You could try to fetch contents using any other method and pass it to `hQuery::fromHTML($contents, $url)`.

The transport functionality of this library is really basic and not it's real power because there are a lot of specialized libraries for fetching data over network (eg. [php-http](https://github.com/php-http), [guzzle](https://github.com/guzzle/guzzle), [cURL](https://secure.php.net/manual/en/ref.curl.php), to name a few).

Please provide at least the URL you are trying to access or try an alternative method of fetching HTML contents.
