### ISSUE TITLE
Use proxy with fromURL

### ISSUE THREAD

**Issue by gmmedia** [duzun/hQuery.php#43]
Hello,
how can I use a proxy with fromURL?

I use that code:
```
$doc = hQuery::fromUrl(
                $url
                , [
                    'Accept'     => $accept_html,
                    'User-Agent' => $user_agent,
                    'Referer'    => $referer,
                ]
 );
```

thank you
Jochen

**Comment by duzun** [comment]
See #26

**Comment by duzun** [comment]
`hQuery::fromUrl()` does not support proxy servers at the moment.
It is my implementation of HTTP requests with caching on the filesystem with no dependencies.
Internally it just opens a TCP socket with `fsockopen()`, composes the HTTP request, sends it through the wire, follows HTTP redirects when needed, reads the HTTP response, decodes & parses it. This is all it does.
In order to support proxy, `hQuery::http_wr()` has to be updated with appropriate logic (`CONNECT` method?), which is not a priority, but PRs are welcome!
