### ISSUE TITLE
Selector .class1.class2 seems to not work

### ISSUE THREAD

**Issue by dbeja** [duzun/hQuery.php#50]
If I want to get all elements that have both class1 and class2, it seems class2 is ignored and all results that have class1 are returned.

I'm using like this:
`$item = $doc->find( '.header-product-info--price.margin-bottom-10' );`

I get all the items that have class **header-product-info--price**, even the ones that don't have class **margin-bottom-10**.

**Comment by duzun** [comment]
Thanks for catching this issue!
I'll add a test for this case an fix it.

**Comment by duzun** [comment]
Fixed in db1f4d0f9beb23e448e7861b36cdaa20b30a9444 [v3.0.2](https://github.com/duzun/hQuery.php/tree/v3.0.2).

Ignore the fact that build fails - it is the stress tests that fail specifically on travis, as I demand hQuery be 10x faster than DOMCrawler.

All other tests pass!

Please, let me know if this fix works for your case.

**Comment by dbeja** [comment]
That was fast. Perfect. Thanks

**Comment by duzun** [comment]
You are welcome!
So, does it work for your case?
