### ISSUE TITLE
How to download the webpage until specific element? like <title>

### ISSUE THREAD

**Issue by khushit-shah** [duzun/hQuery.php#59]
Hi, I only want title of the webpage, and downloading whole page is too slow, is there a way of only downloading till <title>? Maybe this doesn't come under scope of your project. Any Ideas?

**Comment by duzun** [comment]
Hey, I have a few ideas.
Use a library that allows you to read a certain number of bytes in an HTTP(S) request and read the response body in chunks of a certain size (eg 1k), until you find the <title> tag or reach the end of the document or a fixed limit.
You can use the `fsockopen()` + `fwrite()` + `fgets()` functions to acieve this, but you would have to implement the HTTP protocol.
Here is an example of code reading HTTP headers up to the `\n\r` sequence: [HttpSocket.php#L293..L301](https://github.com/duzun/http-socket.php/blob/master/src/HttpSocket.php#L293..L301).
This example is not perfect for your case. I would look for the "<title>" string in the accumulated string `$rsps` rather than in the current chunk `$p`.

**Comment by khushit-shah** [comment]
Thanks, This is great, just what I wanted!
