### ISSUE TITLE
outerHtml() method modifies the content

### ISSUE THREAD

**Issue by PavelFil** [duzun/hQuery.php#82]
We have the HTML code:
```html
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta charset="utf-8">
</head>
<body>
</body>
</html>
```
If we select the `meta[charset]` and call `outerHtml()`, we receive `<meta charset="utf-8" />`. But we expected `<meta charset="utf-8">`.

**Comment by duzun** [comment]
I'm not sure how important this behavior is. Browsers do the same. But I think it wouldn't hurt wither.

**Comment by duzun** [comment]
PTAL at [#9326bb14](https://github.com/duzun/hQuery.php/commit/9326bb14d244385c76adc427537a30b543fc3ca6). 
It addresses your case.
But due to the internal structure of `hQuery`, the top level node is not preserved exactly as in the source HTML. That is not the intention, as I see no use-case for that.
